# Canary release example - small replica set for v2 alongside v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
  labels:
    app: aceest
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      track: canary
  template:
    metadata:
      labels:
        app: aceest
        track: canary
    spec:
      containers:
        - name: aceest
          image: your_dockerhub_username/aceest_fitness:canary
          ports:
            - containerPort: 5000
