apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-rolling
  labels:
    app: aceest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
        - name: aceest
          image: your_dockerhub_username/aceest_fitness:rolling
          ports:
            - containerPort: 5000
